# Generated by Django 5.1.2 on 2025-07-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shortcode_length',
            field=models.PositiveIntegerField(default=6, help_text='Length of shortcodes this user is allowed to create'),
        ),
    ]
