# Generated by Django 5.1.2 on 2025-07-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_comprehensive_quotas'),
        ('accounts', '0002_add_shortcode_length'),
    ]

    operations = [
    ]
