# Generated by Django for proxy metadata support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_remove_filesystem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='proxy_ip',
            field=models.GenericIPAddressField(
                null=True, blank=True,
                help_text="IP address of proxy used for archiving"
            ),
        ),
        migrations.AddField(
            model_name='shortcode',
            name='proxy_country',
            field=models.CharField(
                max_length=2, blank=True,
                help_text="Country code of proxy used for archiving"
            ),
        ),
        migrations.AddField(
            model_name='shortcode',
            name='proxy_provider',
            field=models.CharField(
                max_length=50, blank=True,
                help_text="Proxy provider used for archiving"
            ),
        ),
    ] 