# Generated by Django 5.1.2 on 2025-07-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_add_trust_verification_fields'),
        ('archive', '0004_add_proxy_metadata'),
    ]

    operations = [
    ]
